### ISSUE TITLE
remove replace section in go.mod

### ISSUE THREAD

**Issue by leaxoy** [micro/go-micro#494]
It's a little pain when add replace section to all my micro-service, so can this be removed.

**Comment by asim** [comment]
Do you have a better suggestion? Because if we don't have this replace statement go.mod breaks.

**Comment by leaxoy** [comment]
When I upgrade `go-micro` to v1.4, hit this message.
```
go: github.com/micro/go-micro@v1.4.0 requires
	github.com/micro/go-plugins@v1.1.0 requires
	github.com/golang/lint@v0.0.0-20190313153728-d0100b6bd8b3: parsing go.mod: unexpected module path "golang.org/x/lint"
```

**Comment by leaxoy** [comment]
And it can be solved by adding `replace` section to my go.mod file, but it looks a little annoying. So can we check `go-micro` deps to do something (like pin version, update version, or remove some unused dependency) to remove `replace` section.

**Comment by xpunch** [comment]
Another package dependency issue, why do we need to import github.com/shurcooL/home, I found it's just a website.

**Comment by leaxoy** [comment]
And in my opinion, `go-micro` should be core module and should not depend on any other parts of the stack like `go-plugins`, we can split this entirely or migrate into one package for solve dependency hell.

**Comment by asim** [comment]
I believe the issues should be fixed with 1.5.0

**Comment by xpunch** [comment]
I think the reason why they put all dependencies into **go-micro**, is to simplify usage of this framework. But once they put all dependencies and default implements into **go-micro**, it become very hard to upgrade **go-micro** framework.
Every time when I upgrade **go-micro** framework, I need to download a lot of new packages, and fixing some go mod issues, this is really annoying.
I think provide a core module and a completed module maybe a better alternative.

**Comment by xpunch** [comment]
@asim Thanks very much, the problem is gone after upgrade to v1.5.0.

**Comment by asim** [comment]
Go micro is evolving towards becoming an all encompassing framework for microservices moving beyond communication. We had separation for 4 years but this created a lot of confusion to users about how to leverage all the features. We're now consolidating that effort. While there are currently go mod issues we feel this pain will subside soon. 

Go-micro should not depend on go-plugins but we found strange references based on examples or tests which have now been stripped out.

**Comment by leaxoy** [comment]
The essence for difficult integrate `go-micro` is user must to manual maintain `go.mod` with the `replace` section, this is painful for lots of service, I think. Unless solve `replace`, this problem is still not really solved elegantly.
